/** @type {import("tailwindcss").Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f0",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#2f1400",
        "surface-variant": "#e1e3df",
        "inverse-primary": "#86d7ad",
        "on-background": "#191c1a",
        "background": "#f8faf6",
        "on-surface-variant": "#404943",
        "secondary-fixed-dim": "#ffb780",
        "surface-tint": "#116c4a",
        "tertiary": "#84270f",
        "inverse-surface": "#2e312f",
        "secondary": "#8e4e14",
        "surface-container-highest": "#e1e3df",
        "on-tertiary-fixed": "#3c0700",
        "surface-container": "#eceeea",
        "on-primary-container": "#99ebc0",
        "tertiary-container": "#a43e24",
        "surface": "#f8faf6",
        "on-tertiary-container": "#ffcfc4",
        "primary-fixed": "#a1f4c8",
        "surface-container-lowest": "#ffffff",
        "primary": "#005236",
        "on-primary-fixed": "#002113",
        "secondary-container": "#ffab69",
        "on-surface": "#191c1a",
        "surface-bright": "#f8faf6",
        "error": "#ba1a1a",
        "surface-dim": "#d8dbd7",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#707973",
        "on-tertiary-fixed-variant": "#83260e",
        "on-secondary-container": "#783d01",
        "primary-container": "#126c4a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#6f3800",
        "secondary-fixed": "#ffdcc4",
        "inverse-on-surface": "#eff1ed",
        "tertiary-fixed-dim": "#ffb4a2",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#86d7ad",
        "outline-variant": "#bfc9c1",
        "surface-container-high": "#e7e9e5",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffdad2"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
